name: "Local Hello Action"
description: "Test custom action locally"

inputs:
  name:
    required: true
    default: "User"

runs:
  using: "composite"
  steps:
    - run: |
        echo "Hello ${{ inputs.name }} 👋"
        echo "Current directory:"
        pwd
        echo "Files:"
        ls -l
      shell: bash
