name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # Runs only when you push to main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo (like git clone)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      - name: RUN the docker container
        run: docker run -d -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/myapp

      - name: Health Check
        run: curl http://localhost:3000
