name: Deploy React dist to Mac

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies & build React
      - name: Install and build
        run: |
          npm install
          npm run build

      # Step 4: Setup SSH agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.MAC_SSH_KEY }}

      # Step 5: Copy dist folder to Mac Desktop
      - name: Copy dist to Mac
        run: |
          scp -r ./dist ${{ secrets.MAC_SSH_USER }}@${{ secrets.MAC_SSH_HOST }}:~/Documents/dist
