name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # Runs only when you push to main branch

jobs:
  build_ssh:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo (like git clone)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in REMOTE SSH
      - name: Log in REMOTE SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "✅ SSH Login Successful"
            whoami
            hostname
            pwd
